spring:
  threads:
    virtual:
      enabled: true

  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      pool-name: PricesHikariPool

server:
  shutdown: graceful # Para un cierre limpio en Kubernetes
  port: 8080

resilience4j:
  bulkhead:
    instances:
      priceService:
        # Usamos SEMAPHORE porque los hilos virtuales no necesitan un pool f√≠sico extra
        type: SEMAPHORE
        maxConcurrentCalls: 50 # Debe alinearse con el pool de Hikari